export const CURRENCY_OPTIONS = [
  { code: 'VND', label: 'Việt Nam đồng' },
  { code: 'USD', label: 'Đô la Mỹ' },
  { code: 'EUR', label: 'Euro' },
  { code: 'JPY', label: 'Yên Nhật' },
  { code: 'KRW', label: 'Won Hàn Quốc' },
  { code: 'CNY', label: 'Nhân dân tệ Trung Quốc' },
  { code: 'THB', label: 'Baht Thái' },
  { code: 'SGD', label: 'Đô la Singapore' },
  { code: 'AUD', label: 'Đô la Úc' },
  { code: 'GBP', label: 'Bảng Anh' },
  { code: 'CAD', label: 'Đô la Canada' },
  { code: 'CHF', label: 'Franc Thụy Sĩ' },
  { code: 'HKD', label: 'Đô la Hồng Kông' },
  { code: 'TWD', label: 'Đài tệ' },
  { code: 'MYR', label: 'Ringgit Malaysia' },
  { code: 'IDR', label: 'Rupiah Indonesia' },
  { code: 'PHP', label: 'Peso Philippines' },
  { code: 'INR', label: 'Rupee Ấn Độ' },
  { code: 'NZD', label: 'Đô la New Zealand' },
  { code: 'AED', label: 'Dirham UAE' },
  { code: 'SAR', label: 'Riyal Saudi' },
  { code: 'QAR', label: 'Riyal Qatar' },
  { code: 'KWD', label: 'Dinar Kuwait' },
  { code: 'SEK', label: 'Krona Thụy Điển' },
  { code: 'NOK', label: 'Krone Na Uy' },
  { code: 'DKK', label: 'Krone Đan Mạch' },
  { code: 'MXN', label: 'Peso Mexico' },
  { code: 'BRL', label: 'Real Brazil' },
  { code: 'ZAR', label: 'Rand Nam Phi' },
  { code: 'TRY', label: 'Lira Thổ Nhĩ Kỳ' },
  { code: 'PLN', label: 'Zloty Ba Lan' },
  { code: 'CZK', label: 'Koruna Séc' },
] as const;

export const SUPPORTED_CURRENCY_CODES = CURRENCY_OPTIONS.map(item => item.code);
